name: Lighthouse CI
on:
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install lighthouse
        run: |
          npm install -g lighthouse
          echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Run Template URLs using Lighthouse
        run: |
          lighthouse https://www.perfmatrix.com/ui-performance-testing-tools/ --output=html --output-path=./report.html --save-assets  --quiet --chrome-flags="--headless"  

      - name: Upload Allure Results
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: Results-${{ steps.date.outputs.date }}
          path: ./report.html
