name: jvjn

on:
 workflow_dispatch :
  
jobs:
  ckb-users:
    if: github.event.inputs.option == 'ckb-users' || github.event.inputs.option == 'Both'
      run : |
      echo "ckb-users"  

  
  ckb-planograms:
    if: github.event.inputs.option == 'ckb-planograms'
      run : |
      echo "ckb-planograms"  
